version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 99
  labels:
  - dependencies
  - dependabot
  versioning-strategy: increase
  ignore:
  - dependency-name: react-query
    versions:
    - 3.13.11
  - dependency-name: ember-qunit
    versions:
    - 5.1.4
  - dependency-name: "@clark/eslint-config-ember"
    versions:
    - 2.1.0
  commit-message:
    prefix: chore
    include: scope
